replicaCount: 1

image:
  repository: ghcr.io/quantfitech/otc-price-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  # Database Configuration
  DB_HOST: ""
  DB_PORT: "3306"
  DB_USER: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  
  # Redis Configuration
  REDIS_HOST: ""
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  
  # Application Configuration
  PORT: "8000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "INFO" 