# Default values for si-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/quantfitech/si-monitor
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

schedule:  "*/5 * * * *"

pod:
  annotations: {}
  labels: {}
  securityContext: {}
  env: {}
  secret:
    enable: false
    name: "si-monitor-secrets"
    create: false
    values:
      REDIS_URL: "redis://user:password@hostname:port/db"
      REDIS_HOST: "hostname:port"
      DB_HOST: "mysql-hostname"
      DB_USER: "mysql-username"
      DB_PASSWORD: "mysql-password"
      DB_NAME: "mysql-database"
      ENCRYPTION_KEY: "encryption-key"
  configMap:
    enable: false
    ref: "si-monitor-environment"
    create: false
    values:
      LOG_LEVEL: "warn"
      NODE_ENV: production
      PORT: "3000"
      EXPERIMENTS_ENABLED: "false"
      MAX_LOG_STRING_LENGTH: "200"
      HTTP_PROXY: ""
  configurations:
    enable: true
    secretName: "si-monitor-configurations"
    volumeName: "si-monitor-configurations"
    mountPath: "/config"
    create: true
    values:
      exchange.yaml:
        account: 'SOME_ACCOUNT'
        connections:
          - type: exchange
            label: 'MARKET_MAKING'
            entity: CO
            venue: BTV
            credentials:
                api_key: "AAAAAAAAAAAAAAA"
                api_secret: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
            methods:
              - get_balances
            options:
                exchange_id: bitvavo


# 
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
