# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

image:
  repository: ghcr.io/quantfitech/sim-monitor
  pullPolicy: IfNotPresent
  tag: 1.0.0 # {"$imagepolicy": "default:sim-monitor-production:tag"}

imagePullSecrets: []

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: sim-monitor

pod:
  annotations: {}
  labels: {}
  securityContext: {}
  env: {}
  secret:
    ref: "sim-monitor"
    enable: false
    name: "sim-monitor-secrets"
    create: false
    values:
      REDIS_HOST: "host"
      MYSQL_HOST: "host:3306"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "otc"
  configMap:
    enable: false
    ref: "sim-monitor-environment"
    create: false
    values:
      ENV: dev

# Container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Service Configuration
service:
  type: ClusterIP
  port: 80
  # service annotations
  annotations: {}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
