image:
  repository: 848009531425.dkr.ecr.ap-northeast-1.amazonaws.com/si-monitor
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""


# docs: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# docs: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

pod:
  annotations: {}
  labels: {}
  securityContext: {}
  env: {}
  secret:
    enable: false
    name: "fallback-price-secrets"
    create: false
    values:
      DATADOG_API_KEY: "DATADOG_API_KEY-FqMxQn:::"
      DB_PASSWORD: "RDS_PASSWORD-9yeWJP:::"
  configMap:
    enable: false
    ref: "fallback-price-environment"
    create: false
    values:
      LOG_LEVEL: "warn"
      NODE_ENV: production
      PORT: "3000"
      EXPERIMENTS_ENABLED: "false"
      MAX_LOG_STRING_LENGTH: "200"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 2000m
    memory: 2Gi
 
# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# configuration path
configPath: "/config"

# pod's node selector
nodeSelector: {}

# pod's node tolerations
tolerations: []

# pod's node affinity
affinity: {}
