apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fallback-price.fullname" . }}
  {{- with .Values.cronJobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
  labels:
    {{- include "fallback-price.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 12
  successfulJobsHistoryLimit: 6
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
            - name: si-monitor
              image: 848009531425.dkr.ecr.ap-northeast-1.amazonaws.com/si-monitor:latest
              imagePullPolicy: Always
              command:
                - python3
                - main.py
                - --file
                - /config
              env:
                - name: ENV
                  value: {{ .Values.environment }}
              envFrom:
                - secretRef:
                    name: si-monitor-environment
          volumes:
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 8}}
          {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}

