# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/quantfitech/fx_rate_service
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

pod:
  annotations: {}
  labels: {}
  securityContext: {}
  env: {}
  secret:
    enable: false
    name: "fx-rate-secrets"
    create: false
    values:
      REDIS_HOST: "redis://user:password@hostname:port/db"
  configMap:
    enable: false
    ref: "fx-rate-environment"
    create: false
    values:
      LOG_LEVEL: "warn"
      NODE_ENV: production
      MAX_LOG_STRING_LENGTH: "200"

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
