image:
  repository: ghcr.io/quantfitech/otc_price_service
  tag: "v1.4.0"  # The version we pushed earlier
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-app-credentials

serviceAccount:
  create: true
  name: otc-price-service

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  # Database Configuration
  DB_HOST: "104.198.119.222"
  DB_PORT: "3306"
  DB_USER: "otc_user"
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: db-password
  DB_NAME: "otcdb"
  
  # Redis Configuration
  REDIS_HOST: "10.121.12.251"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  
  # Application Configuration
  PORT: "8000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "INFO" 