replicaCount: 2

image:
  repository: ghcr.io/quantfitech/otc-api
  pullPolicy: IfNotPresent
  tag: "{{ .Values.imageTag | default .Chart.AppVersion }}"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  DB_HOST: <postgres-host>
  DB_PORT: 5432
  DB_USER: <postgres-user>
  DB_PASSWORD: <postgres-password>
  DB_NAME: otcapi
  REDIS_HOST: <redis-host>
  REDIS_PORT: 6379
  REDIS_PASSWORD: <redis-password>
  JWT_SECRET: <jwt-secret>
  API_KEY: <api-key>

secrets:
  dbPassword:
    secretName: otc-api-db-password
    key: password
  jwtSecret:
    secretName: otc-api-jwt-secret
    key: secret
  apiKey:
    secretName: otc-api-key
    key: key

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80 