replicaCount: 2

image:
  repository: ghcr.io/quantfitech/otc-api
  pullPolicy: IfNotPresent
  tag: "{{ .Values.imageTag | default .Chart.AppVersion }}"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  DB_HOST: "104.198.119.222"
  DB_PORT: 3306
  DB_USER: "otc_user"
  DB_PASSWORD: <postgres-password>
  DB_NAME: otcapi
  REDIS_HOST: "10.121.12.251"
  REDIS_PORT: 6379
  PORT: "3000"

secrets:
  dbPassword:
    secretName: otc-db-password
    key: db-password

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80 