image:
  repository: ghcr.io/quantfitech/otc-api
  tag: "{{ .Values.imageTag | default .Chart.AppVersion }}"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-app-credentials

serviceAccount:
  create: true
  name: otc-api

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  # Database Configuration
  DB_HOST: "34.146.134.82"
  DB_PORT: "3306"
  DB_USER: "otc_user"
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: otc-db-password
        key: db-password
  DB_NAME: "otcdb"
  
  # Redis Configuration
  REDIS_URL: "redis://10.121.12.251:6379"
  
  # Application Configuration
  PORT: "3000"
  SERVICE_NAME: "otc-api"
  ENV: "production"
  LOG_LEVEL: "INFO" 