# Default values for otc-api.

nameOverride: ""
fullnameOverride: ""

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 4

image:
  repository: ghcr.io/quantfitech/otc-api
  pullPolicy: IfNotPresent
  tag: 1.0.0 # {"$imagepolicy": "default:otc-api-production:tag"}

imagePullSecrets: []

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: otc-api

pod:
  annotations: {}
  labels: {}
  securityContext: {}
  env: {}
  secret:
    ref: "otc-api"
    enable: false
    name: "otc-api-secrets"
    create: false
    values:
      REDIS_URL: "redis://user:password@hostname:port/db"
      DB_HOST: "host:3306"
      DB_USER: "username"
      DB_PASSWORD: "password"
      DB_NAME: "otc"
      ENCRYPTION_KEY: "encryption-key"
  configMap:
    enable: false
    ref: "otc-api-environment"
    create: false
    values:
      LOG_LEVEL: "warn"
      NODE_ENV: production
      PORT: "3000"
      EXPERIMENTS_ENABLED: "false"
      MAX_LOG_STRING_LENGTH: "200"

# Container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Service Configuration
service:
  type: ClusterIP
  port: 80
  # service annotations
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  enable: true
readinessProbe:
  enable: true

# Horizontal Pod Autoscaler settings
hpa:
  enabled: false
  minReplicas: 4
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
