name: Deploy to GCP

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.4.2)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure kubectl
        run: |
          echo "Getting credentials for cluster: ${{ vars.GCP_CLUSTER_NAME }} in region: ${{ vars.GCP_REGION }}"
          gcloud container clusters get-credentials "${{ vars.GCP_CLUSTER_NAME }}" --region "${{ vars.GCP_REGION }}" --project "${{ vars.GCP_PROJECT_ID }}"

      - name: Update version in deploy script
        run: |
          sed -i "s/tag: v[0-9]\+\.[0-9]\+\.[0-9]\+/tag: ${{ github.event.inputs.version }}/" otc-price-service/scripts/deploy.sh
          sed -i "s/tag: \"v[0-9]\+\.[0-9]\+\.[0-9]\+\"/tag: \"${{ github.event.inputs.version }}\"/" otc-price-service/helm/values-gcp.yaml

      - name: Deploy to GCP
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd otc-price-service/scripts
          chmod +x deploy.sh
          GH_USERNAME=${{ vars.GH_USERNAME }} GH_TOKEN=$GH_TOKEN ./deploy.sh 