name: Deploy to GCP

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.4.2)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }}

      - name: Update version in deploy script
        run: |
          sed -i "s/tag: v[0-9]\+\.[0-9]\+\.[0-9]\+/tag: ${{ github.event.inputs.version }}/" otc-price-service/scripts/deploy.sh
          sed -i "s/tag: \"v[0-9]\+\.[0-9]\+\.[0-9]\+\"/tag: \"${{ github.event.inputs.version }}\"/" otc-price-service/helm/values-gcp.yaml

      - name: Deploy to GCP
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd otc-price-service/scripts
          chmod +x deploy.sh
          ./deploy.sh 