name: Deploy to GCP

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.4.2)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure kubectl
        env:
          CLUSTER_NAME: ${{ vars.GCP_CLUSTER_NAME }}
          CLUSTER_REGION: ${{ vars.GCP_REGION }}
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials "${CLUSTER_NAME}" --region "${CLUSTER_REGION}" --project "${PROJECT_ID}"

      - name: Update version in deploy script
        run: |
          sed -i "s/tag: v[0-9]\+\.[0-9]\+\.[0-9]\+/tag: ${{ github.event.inputs.version }}/" otc-price-service/scripts/deploy.sh
          sed -i "s/tag: \"v[0-9]\+\.[0-9]\+\.[0-9]\+\"/tag: \"${{ github.event.inputs.version }}\"/" otc-price-service/helm/values-gcp.yaml

      - name: Extract environment variables
        id: extract-env
        run: |
          DB_HOST=$(yq '.env.DB_HOST' otc-price-service/helm/values-gcp.yaml)
          DB_PORT=$(yq '.env.DB_PORT' otc-price-service/helm/values-gcp.yaml)
          DB_USER=$(yq '.env.DB_USER' otc-price-service/helm/values-gcp.yaml)
          DB_NAME=$(yq '.env.DB_NAME' otc-price-service/helm/values-gcp.yaml)
          REDIS_HOST=$(yq '.env.REDIS_HOST' otc-price-service/helm/values-gcp.yaml)
          REDIS_PORT=$(yq '.env.REDIS_PORT' otc-price-service/helm/values-gcp.yaml)
          REDIS_PASSWORD=$(yq '.env.REDIS_PASSWORD' otc-price-service/helm/values-gcp.yaml)
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "REDIS_HOST=$REDIS_HOST" >> $GITHUB_ENV
          echo "REDIS_PORT=$REDIS_PORT" >> $GITHUB_ENV
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> $GITHUB_ENV

      - name: Deploy to GCP
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd otc-price-service/scripts
          chmod +x deploy.sh
          GH_USERNAME=denis-maley GH_TOKEN=$GH_TOKEN \
          DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_USER=$DB_USER DB_NAME=$DB_NAME \
          REDIS_HOST=$REDIS_HOST REDIS_PORT=$REDIS_PORT REDIS_PASSWORD=$REDIS_PASSWORD \
          ./deploy.sh 