on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-tags:
    runs-on: ["ubuntu-latest"]
    permissions:
      contents: read
      packages: read
      attestations: write
      id-token: write
    steps:
      - name: generate token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.MINIQUANTBOT_APPID }}
          private-key: ${{ secrets.MINIQUANTBOT_PKEY }}
          # owner is required, otherwise the creds will fail the checkout step
          owner: ${{ github.repository_owner }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
          submodules: recursive
          token: ${{ steps.app_token.outputs.token }}

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          keep-env-derivations: true
          keep-outputs: true
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-common

      - run: .github/workflows/update-tags.fish
        env:
          OCI_USERNAME: ${{ github.repository_owner }}
          OCI_PASSWORD: ${{ steps.app_token.outputs.token }}
          
