name: validate

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - review_requested
      - ready_for_review
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  validate:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          keep-env-derivations: true
          keep-outputs: true
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-common

      - name: validate
        run: .github/workflows/validate.sh
        shell: nix develop --quiet --command fish {0}
